package initialize

import (
	. "waugzee/internal/models"
)

func intPtr(i int) *int {
	return &i
}

func cartridgeTypePtr(ct CartridgeType) *CartridgeType {
	return &ct
}

func getStylusesData() []Stylus {
	return []Stylus{
		{
			Brand:                   "Audio-Technica",
			Model:                   "AT3600L",
			Type:                    StylusTypeConical,
			CartridgeType:           cartridgeTypePtr(CartridgeTypeMovingMagnet),
			RecommendedReplaceHours: intPtr(400),
			IsVerified:              true,
		},
		{
			Brand:                   "Audio-Technica",
			Model:                   "AT-VM95C",
			Type:                    StylusTypeConical,
			CartridgeType:           cartridgeTypePtr(CartridgeTypeMovingMagnet),
			RecommendedReplaceHours: intPtr(500),
			IsVerified:              true,
		},
		{
			Brand:                   "Audio-Technica",
			Model:                   "AT-VM95E",
			Type:                    StylusTypeElliptical,
			CartridgeType:           cartridgeTypePtr(CartridgeTypeMovingMagnet),
			RecommendedReplaceHours: intPtr(300),
			IsVerified:              true,
		},
		{
			Brand:                   "Audio-Technica",
			Model:                   "AT-VM95EN",
			Type:                    StylusTypeElliptical,
			CartridgeType:           cartridgeTypePtr(CartridgeTypeMovingMagnet),
			RecommendedReplaceHours: intPtr(400),
			IsVerified:              true,
		},
		{
			Brand:                   "Audio-Technica",
			Model:                   "AT-VM95ML",
			Type:                    StylusTypeMicroLine,
			CartridgeType:           cartridgeTypePtr(CartridgeTypeMovingMagnet),
			RecommendedReplaceHours: intPtr(1000),
			IsVerified:              true,
		},
		{
			Brand:                   "Audio-Technica",
			Model:                   "AT95E",
			Type:                    StylusTypeElliptical,
			CartridgeType:           cartridgeTypePtr(CartridgeTypeMovingMagnet),
			RecommendedReplaceHours: intPtr(400),
			IsVerified:              true,
		},
		{
			Brand:                   "Ortofon",
			Model:                   "2M Red",
			Type:                    StylusTypeElliptical,
			CartridgeType:           cartridgeTypePtr(CartridgeTypeMovingMagnet),
			RecommendedReplaceHours: intPtr(1000),
			IsVerified:              true,
		},
		{
			Brand:                   "Ortofon",
			Model:                   "OM5E",
			Type:                    StylusTypeElliptical,
			CartridgeType:           cartridgeTypePtr(CartridgeTypeMovingMagnet),
			RecommendedReplaceHours: intPtr(1000),
			IsVerified:              true,
		},
		{
			Brand:                   "Nagaoka",
			Model:                   "MP-110",
			Type:                    StylusTypeElliptical,
			CartridgeType:           cartridgeTypePtr(CartridgeTypeMovingMagnet),
			RecommendedReplaceHours: intPtr(500),
			IsVerified:              true,
		},
		{
			Brand:                   "Goldring",
			Model:                   "E2",
			Type:                    StylusTypeConical,
			CartridgeType:           cartridgeTypePtr(CartridgeTypeMovingMagnet),
			RecommendedReplaceHours: intPtr(500),
			IsVerified:              true,
		},
		{
			Brand:                   "Goldring",
			Model:                   "E3",
			Type:                    StylusTypeElliptical,
			CartridgeType:           cartridgeTypePtr(CartridgeTypeMovingMagnet),
			RecommendedReplaceHours: intPtr(1000),
			IsVerified:              true,
		},
		{
			Brand:                   "Grado",
			Model:                   "Prestige Black3",
			Type:                    StylusTypeElliptical,
			CartridgeType:           cartridgeTypePtr(CartridgeTypeOther),
			RecommendedReplaceHours: intPtr(800),
			IsVerified:              true,
		},
		{
			Brand:                   "Grado",
			Model:                   "Prestige Green3",
			Type:                    StylusTypeElliptical,
			CartridgeType:           cartridgeTypePtr(CartridgeTypeOther),
			RecommendedReplaceHours: intPtr(800),
			IsVerified:              true,
		},
		{
			Brand:                   "Shure",
			Model:                   "M97xE",
			Type:                    StylusTypeElliptical,
			CartridgeType:           cartridgeTypePtr(CartridgeTypeMovingMagnet),
			RecommendedReplaceHours: intPtr(750),
			IsVerified:              true,
		},
		{
			Brand:                   "Audio-Technica",
			Model:                   "VM540ML",
			Type:                    StylusTypeMicroLine,
			CartridgeType:           cartridgeTypePtr(CartridgeTypeMovingMagnet),
			RecommendedReplaceHours: intPtr(1000),
			IsVerified:              true,
		},
		{
			Brand:                   "Audio-Technica",
			Model:                   "VM750SH",
			Type:                    StylusTypeShibata,
			CartridgeType:           cartridgeTypePtr(CartridgeTypeMovingMagnet),
			RecommendedReplaceHours: intPtr(800),
			IsVerified:              true,
		},
		{
			Brand:                   "Ortofon",
			Model:                   "2M Blue",
			Type:                    StylusTypeElliptical,
			CartridgeType:           cartridgeTypePtr(CartridgeTypeMovingMagnet),
			RecommendedReplaceHours: intPtr(1000),
			IsVerified:              true,
		},
		{
			Brand:                   "Ortofon",
			Model:                   "2M Bronze",
			Type:                    StylusTypeLineContact,
			CartridgeType:           cartridgeTypePtr(CartridgeTypeMovingMagnet),
			RecommendedReplaceHours: intPtr(1000),
			IsVerified:              true,
		},
		{
			Brand:                   "Ortofon",
			Model:                   "2M Black",
			Type:                    StylusTypeShibata,
			CartridgeType:           cartridgeTypePtr(CartridgeTypeMovingMagnet),
			RecommendedReplaceHours: intPtr(1000),
			IsVerified:              true,
		},
		{
			Brand:                   "Nagaoka",
			Model:                   "MP-150",
			Type:                    StylusTypeElliptical,
			CartridgeType:           cartridgeTypePtr(CartridgeTypeMovingMagnet),
			RecommendedReplaceHours: intPtr(500),
			IsVerified:              true,
		},
		{
			Brand:                   "Nagaoka",
			Model:                   "MP-200",
			Type:                    StylusTypeElliptical,
			CartridgeType:           cartridgeTypePtr(CartridgeTypeMovingMagnet),
			RecommendedReplaceHours: intPtr(500),
			IsVerified:              true,
		},
		{
			Brand:                   "Grado",
			Model:                   "Prestige Blue3",
			Type:                    StylusTypeElliptical,
			CartridgeType:           cartridgeTypePtr(CartridgeTypeOther),
			RecommendedReplaceHours: intPtr(800),
			IsVerified:              true,
		},
		{
			Brand:                   "Grado",
			Model:                   "Prestige Red3",
			Type:                    StylusTypeElliptical,
			CartridgeType:           cartridgeTypePtr(CartridgeTypeOther),
			RecommendedReplaceHours: intPtr(800),
			IsVerified:              true,
		},
		{
			Brand:                   "Grado",
			Model:                   "Prestige Gold3",
			Type:                    StylusTypeElliptical,
			CartridgeType:           cartridgeTypePtr(CartridgeTypeOther),
			RecommendedReplaceHours: intPtr(800),
			IsVerified:              true,
		},
		{
			Brand:                   "Grado",
			Model:                   "Platinum3",
			Type:                    StylusTypeElliptical,
			CartridgeType:           cartridgeTypePtr(CartridgeTypeOther),
			RecommendedReplaceHours: intPtr(800),
			IsVerified:              true,
		},
		{
			Brand:                   "Grado",
			Model:                   "Sonata3",
			Type:                    StylusTypeElliptical,
			CartridgeType:           cartridgeTypePtr(CartridgeTypeOther),
			RecommendedReplaceHours: intPtr(800),
			IsVerified:              true,
		},
		{
			Brand:                   "Audio-Technica",
			Model:                   "AT-OC9XML",
			Type:                    StylusTypeMicroLine,
			CartridgeType:           cartridgeTypePtr(CartridgeTypeMovingCoil),
			RecommendedReplaceHours: intPtr(1000),
			IsVerified:              true,
		},
		{
			Brand:                   "Audio-Technica",
			Model:                   "AT-OC9/III",
			Type:                    StylusTypeMicroLine,
			CartridgeType:           cartridgeTypePtr(CartridgeTypeMovingCoil),
			RecommendedReplaceHours: intPtr(1000),
			IsVerified:              true,
		},
		{
			Brand:                   "Audio-Technica",
			Model:                   "AT33PTG/II",
			Type:                    StylusTypeLineContact,
			CartridgeType:           cartridgeTypePtr(CartridgeTypeMovingCoil),
			RecommendedReplaceHours: intPtr(1000),
			IsVerified:              true,
		},
		{
			Brand:                   "Ortofon",
			Model:                   "2M Black LVB 250",
			Type:                    StylusTypeShibata,
			CartridgeType:           cartridgeTypePtr(CartridgeTypeMovingMagnet),
			RecommendedReplaceHours: intPtr(1000),
			IsVerified:              true,
		},
		{
			Brand:                   "Ortofon",
			Model:                   "Quintet Black S",
			Type:                    StylusTypeShibata,
			CartridgeType:           cartridgeTypePtr(CartridgeTypeMovingCoil),
			RecommendedReplaceHours: intPtr(1500),
			IsVerified:              true,
		},
		{
			Brand:                   "Ortofon",
			Model:                   "Cadenza Red",
			Type:                    StylusTypeLineContact,
			CartridgeType:           cartridgeTypePtr(CartridgeTypeMovingCoil),
			RecommendedReplaceHours: intPtr(1500),
			IsVerified:              true,
		},
		{
			Brand:                   "Ortofon",
			Model:                   "Cadenza Black",
			Type:                    StylusTypeShibata,
			CartridgeType:           cartridgeTypePtr(CartridgeTypeMovingCoil),
			RecommendedReplaceHours: intPtr(1500),
			IsVerified:              true,
		},
		{
			Brand:                   "Hana",
			Model:                   "EL",
			Type:                    StylusTypeElliptical,
			CartridgeType:           cartridgeTypePtr(CartridgeTypeMovingCoil),
			RecommendedReplaceHours: intPtr(1500),
			IsVerified:              true,
		},
		{
			Brand:                   "Hana",
			Model:                   "SL",
			Type:                    StylusTypeShibata,
			CartridgeType:           cartridgeTypePtr(CartridgeTypeMovingCoil),
			RecommendedReplaceHours: intPtr(1500),
			IsVerified:              true,
		},
		{
			Brand:                   "Hana",
			Model:                   "ML",
			Type:                    StylusTypeMicroLine,
			CartridgeType:           cartridgeTypePtr(CartridgeTypeMovingCoil),
			RecommendedReplaceHours: intPtr(1500),
			IsVerified:              true,
		},
		{
			Brand:                   "Denon",
			Model:                   "DL-103",
			Type:                    StylusTypeConical,
			CartridgeType:           cartridgeTypePtr(CartridgeTypeMovingCoil),
			RecommendedReplaceHours: intPtr(1500),
			IsVerified:              true,
		},
		{
			Brand:                   "Denon",
			Model:                   "DL-110",
			Type:                    StylusTypeElliptical,
			CartridgeType:           cartridgeTypePtr(CartridgeTypeMovingCoil),
			RecommendedReplaceHours: intPtr(1500),
			IsVerified:              true,
		},
		{
			Brand:                   "Sumiko",
			Model:                   "Blue Point No. 3",
			Type:                    StylusTypeElliptical,
			CartridgeType:           cartridgeTypePtr(CartridgeTypeMovingCoil),
			RecommendedReplaceHours: intPtr(1500),
			IsVerified:              true,
		},
		{
			Brand:                   "Sumiko",
			Model:                   "Moonstone",
			Type:                    StylusTypeElliptical,
			CartridgeType:           cartridgeTypePtr(CartridgeTypeMovingMagnet),
			RecommendedReplaceHours: intPtr(1200),
			IsVerified:              true,
		},
		{
			Brand:                   "Sumiko",
			Model:                   "Rainier",
			Type:                    StylusTypeElliptical,
			CartridgeType:           cartridgeTypePtr(CartridgeTypeMovingMagnet),
			RecommendedReplaceHours: intPtr(1000),
			IsVerified:              true,
		},
		{
			Brand:                   "Goldring",
			Model:                   "E4",
			Type:                    StylusTypeElliptical,
			CartridgeType:           cartridgeTypePtr(CartridgeTypeMovingMagnet),
			RecommendedReplaceHours: intPtr(1000),
			IsVerified:              true,
		},
		{
			Brand:                   "Ortofon",
			Model:                   "Quintet Red",
			Type:                    StylusTypeElliptical,
			CartridgeType:           cartridgeTypePtr(CartridgeTypeMovingCoil),
			RecommendedReplaceHours: intPtr(1500),
			IsVerified:              true,
		},
		{
			Brand:                   "Zu Audio",
			Model:                   "DL-103 Mk. II",
			Type:                    StylusTypeConical,
			CartridgeType:           cartridgeTypePtr(CartridgeTypeMovingCoil),
			RecommendedReplaceHours: intPtr(1500),
			IsVerified:              true,
		},
		{
			Brand:                   "Hana",
			Model:                   "Umami Red",
			Type:                    StylusTypeMicroLine,
			CartridgeType:           cartridgeTypePtr(CartridgeTypeMovingCoil),
			RecommendedReplaceHours: intPtr(1500),
			IsVerified:              true,
		},
		{
			Brand:                   "Audio-Technica",
			Model:                   "AT-VM95SP",
			Type:                    StylusTypeConical,
			CartridgeType:           cartridgeTypePtr(CartridgeTypeMovingMagnet),
			RecommendedReplaceHours: intPtr(500),
			IsVerified:              true,
		},
		{
			Brand:                   "Audio-Technica",
			Model:                   "AT-VM95SH",
			Type:                    StylusTypeShibata,
			CartridgeType:           cartridgeTypePtr(CartridgeTypeMovingMagnet),
			RecommendedReplaceHours: intPtr(800),
			IsVerified:              true,
		},
		{
			Brand:                   "Ortofon",
			Model:                   "2M Silver",
			Type:                    StylusTypeElliptical,
			CartridgeType:           cartridgeTypePtr(CartridgeTypeMovingMagnet),
			RecommendedReplaceHours: intPtr(1000),
			IsVerified:              true,
		},
		{
			Brand:                   "Nagaoka",
			Model:                   "MP-300",
			Type:                    StylusTypeElliptical,
			CartridgeType:           cartridgeTypePtr(CartridgeTypeMovingMagnet),
			RecommendedReplaceHours: intPtr(500),
			IsVerified:              true,
		},
		{
			Brand:                   "Nagaoka",
			Model:                   "MP-500",
			Type:                    StylusTypeLineContact,
			CartridgeType:           cartridgeTypePtr(CartridgeTypeMovingMagnet),
			RecommendedReplaceHours: intPtr(1000),
			IsVerified:              true,
		},
	}
}
